use lsp_types::{
    CompletionItem, CompletionItemKind, Documentation, InsertTextFormat, MarkupContent, MarkupKind,
};

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum CompletionContext {
    Value,
    Type,
    Attribute,
}

pub struct CompletionSpec {
    pub label: &'static str,
    pub kind: CompletionItemKind,
    pub detail: &'static str,
    pub documentation: &'static str,
    pub insert_text: &'static str,
    pub insert_text_format: Option<InsertTextFormat>,
    pub sort_group: &'static str,
    pub contexts: &'static [CompletionContext],
}

const VALUE_CONTEXTS: &[CompletionContext] = &[CompletionContext::Value];
const VALUE_AND_TYPE_CONTEXTS: &[CompletionContext] =
    &[CompletionContext::Value, CompletionContext::Type];
const ATTRIBUTE_CONTEXTS: &[CompletionContext] = &[CompletionContext::Attribute];

pub const KEYWORD_SPECS: &[CompletionSpec] = &[
    CompletionSpec {
        label: "match",
        kind: CompletionItemKind::KEYWORD,
        detail: "Pattern matching expression",
        documentation: "Branch on a value with pattern matching.\n\n```shadml\nmatch value\n  | Pattern -> result\n```",
        insert_text: "match ${1:value}\n  | ${2:pattern} -> ${3:result}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "let",
        kind: CompletionItemKind::KEYWORD,
        detail: "Introduces local bindings",
        documentation: "Introduce local bindings and evaluate a body expression.\n\n```shadml\nlet x = value\nin body\n```",
        insert_text: "let ${1:name} = ${2:value}\nin ${3:body}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "in",
        kind: CompletionItemKind::KEYWORD,
        detail: "Body of a let expression",
        documentation: "Marks the body that sees the preceding `let` bindings.",
        insert_text: "in",
        insert_text_format: None,
        sort_group: "11",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "if",
        kind: CompletionItemKind::KEYWORD,
        detail: "Conditional expression",
        documentation: "Choose between two expressions based on a boolean condition.\n\n```shadml\nif condition\n  then when_true\n  else when_false\n```",
        insert_text: "if ${1:condition}\n  then ${2:when_true}\n  else ${3:when_false}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "then",
        kind: CompletionItemKind::KEYWORD,
        detail: "Then branch of an if expression",
        documentation: "Introduces the true branch of an `if` expression.",
        insert_text: "then",
        insert_text_format: None,
        sort_group: "11",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "else",
        kind: CompletionItemKind::KEYWORD,
        detail: "Else branch of an if expression",
        documentation: "Introduces the false branch of an `if` expression.",
        insert_text: "else",
        insert_text_format: None,
        sort_group: "11",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "where",
        kind: CompletionItemKind::KEYWORD,
        detail: "Local definitions",
        documentation: "Attach local bindings to a declaration.\n\n```shadml\nf x = body\nwhere\n  helper = x + 1\n```",
        insert_text: "where\n  ${1:name} = ${2:value}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "data",
        kind: CompletionItemKind::KEYWORD,
        detail: "Algebraic data type declaration",
        documentation: "Declare an algebraic data type and its constructors.\n\n```shadml\ndata Option a = Some a | None\n```",
        insert_text: "data ${1:Type} ${2:a} = ${3:Constructor}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "alias",
        kind: CompletionItemKind::KEYWORD,
        detail: "Type alias declaration",
        documentation: "Define a named alias for a type expression.\n\n```shadml\nalias Vec4f = Vec 4 F32\n```",
        insert_text: "alias ${1:Alias} = ${2:Type}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "class",
        kind: CompletionItemKind::KEYWORD,
        detail: "Type class declaration",
        documentation: "Declare a type class interface.\n\n```shadml\nclass Functor f where\n  fmap : (a -> b) -> f a -> f b\n```",
        insert_text: "class ${1:Class} ${2:f} where\n  ${3:member} : ${4:Type}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "instance",
        kind: CompletionItemKind::KEYWORD,
        detail: "Type class instance",
        documentation: "Implement a type class for a concrete type.\n\n```shadml\ninstance Functor Option where\n  fmap f value = value\n```",
        insert_text: "instance ${1:Class} ${2:Type} where\n  ${3:member} = ${4:impl}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "module",
        kind: CompletionItemKind::KEYWORD,
        detail: "Module declaration",
        documentation: "Declare the module name at the top of the file.",
        insert_text: "module ${1:Main}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "import",
        kind: CompletionItemKind::KEYWORD,
        detail: "Import declaration",
        documentation: "Bring another module into scope.",
        insert_text: "import ${1:Module}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "do",
        kind: CompletionItemKind::KEYWORD,
        detail: "Do notation block",
        documentation: "Sequence monadic statements in a block.",
        insert_text: "do\n  ${1:statement}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "forall",
        kind: CompletionItemKind::KEYWORD,
        detail: "Universal quantification",
        documentation: "Bind type variables explicitly in a type expression.\n\n```shadml\nforall a. a -> a\n```",
        insert_text: "forall ${1:a}. ${2:type}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "case",
        kind: CompletionItemKind::KEYWORD,
        detail: "Case expression",
        documentation: "Alternative spelling for a pattern matching expression.",
        insert_text: "case ${1:value} of\n  | ${2:pattern} -> ${3:result}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "10",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "of",
        kind: CompletionItemKind::KEYWORD,
        detail: "Case arms",
        documentation: "Introduces the pattern arms of a `case` or `match` expression.",
        insert_text: "of",
        insert_text_format: None,
        sort_group: "11",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "infixl",
        kind: CompletionItemKind::KEYWORD,
        detail: "Left-associative fixity",
        documentation: "Declare left-associative precedence for an operator.",
        insert_text: "infixl ${1:6} ${2:operator}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "12",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "infixr",
        kind: CompletionItemKind::KEYWORD,
        detail: "Right-associative fixity",
        documentation: "Declare right-associative precedence for an operator.",
        insert_text: "infixr ${1:6} ${2:operator}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "12",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "infix",
        kind: CompletionItemKind::KEYWORD,
        detail: "Non-associative fixity",
        documentation: "Declare non-associative precedence for an operator.",
        insert_text: "infix ${1:6} ${2:operator}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "12",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "deriving",
        kind: CompletionItemKind::KEYWORD,
        detail: "Automatic instance derivation",
        documentation: "Request compiler-generated type class instances.",
        insert_text: "deriving (${1:Eq})",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "12",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
];

pub const TYPE_SPECS: &[CompletionSpec] = &[
    CompletionSpec {
        label: "I32",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "32-bit signed integer",
        documentation: "Signed 32-bit integer type that lowers to `i32` in WGSL.",
        insert_text: "I32",
        insert_text_format: None,
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "U32",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "32-bit unsigned integer",
        documentation: "Unsigned 32-bit integer type that lowers to `u32` in WGSL.",
        insert_text: "U32",
        insert_text_format: None,
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "F32",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "32-bit floating point",
        documentation: "32-bit floating point scalar that lowers to `f32` in WGSL.",
        insert_text: "F32",
        insert_text_format: None,
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Bool",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Boolean type",
        documentation: "Boolean scalar type that lowers to `bool` in WGSL.",
        insert_text: "Bool",
        insert_text_format: None,
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Scalar",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Scalar alias",
        documentation: "Scalar tensor alias. `Scalar F32` and `Sca F32` normalize to `F32`.",
        insert_text: "Scalar ${1:F32}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Sca",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Alias for Scalar",
        documentation: "Short alias for `Scalar`.",
        insert_text: "Sca ${1:F32}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Tensor",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Dependent tensor type",
        documentation: "Fixed-size tensor type parameterized by a type-level extent and element type.\n\n```shadml\nTensor 16 F32\n```",
        insert_text: "Tensor ${1:16} ${2:F32}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Ten",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Alias for Tensor",
        documentation: "Short alias for `Tensor`.",
        insert_text: "Ten ${1:16} ${2:F32}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Vector",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Vector type",
        documentation: "Fixed-length vector type parameterized by a type-level dimension and scalar type.\n\n```shadml\nVector 3 F32\n```",
        insert_text: "Vector ${1:3} ${2:F32}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Vec",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Alias for Vector",
        documentation: "Short alias for `Vector`.\n\n```shadml\nVec 3 F32\n```",
        insert_text: "Vec ${1:3} ${2:F32}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Matrix",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Matrix type",
        documentation: "Matrix type parameterized by row count, column count, and scalar type.\n\n```shadml\nMatrix 4 4 F32\n```",
        insert_text: "Matrix ${1:4} ${2:4} ${3:F32}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Mat",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Alias for Matrix",
        documentation: "Short alias for `Matrix`.\n\n```shadml\nMat 4 4 F32\n```",
        insert_text: "Mat ${1:4} ${2:4} ${3:F32}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Option",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Optional value",
        documentation: "Builtin algebraic data type for values that may be absent.\n\n```shadml\nOption F32\n```",
        insert_text: "Option ${1:F32}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Result",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Success or error value",
        documentation: "Builtin algebraic data type with `Ok value` and `Err message` constructors.\n\n```shadml\nResult F32\n```",
        insert_text: "Result ${1:F32}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Pair",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Pair data type",
        documentation: "Builtin product type.\n\n```shadml\nPair F32 Bool\n```",
        insert_text: "Pair ${1:F32} ${2:Bool}",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "String",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "String type",
        documentation: "String type for source-level programming support.",
        insert_text: "String",
        insert_text_format: None,
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
    CompletionSpec {
        label: "Char",
        kind: CompletionItemKind::TYPE_PARAMETER,
        detail: "Character type",
        documentation: "Single Unicode scalar value.",
        insert_text: "Char",
        insert_text_format: None,
        sort_group: "20",
        contexts: VALUE_AND_TYPE_CONTEXTS,
    },
];

pub const BUILTIN_SPECS: &[CompletionSpec] = &[
    CompletionSpec {
        label: "vec2",
        kind: CompletionItemKind::FUNCTION,
        detail: "Construct Vec 2",
        documentation: "Construct a two-component vector value.",
        insert_text: "vec2",
        insert_text_format: None,
        sort_group: "31",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "vec3",
        kind: CompletionItemKind::FUNCTION,
        detail: "Construct Vec 3",
        documentation: "Construct a three-component vector value.",
        insert_text: "vec3",
        insert_text_format: None,
        sort_group: "31",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "vec4",
        kind: CompletionItemKind::FUNCTION,
        detail: "Construct Vec 4",
        documentation: "Construct a four-component vector value.",
        insert_text: "vec4",
        insert_text_format: None,
        sort_group: "31",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "sin",
        kind: CompletionItemKind::FUNCTION,
        detail: "Sine",
        documentation: "WGSL math builtin for sine.",
        insert_text: "sin",
        insert_text_format: None,
        sort_group: "31",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "cos",
        kind: CompletionItemKind::FUNCTION,
        detail: "Cosine",
        documentation: "WGSL math builtin for cosine.",
        insert_text: "cos",
        insert_text_format: None,
        sort_group: "31",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "mix",
        kind: CompletionItemKind::FUNCTION,
        detail: "Linear interpolation",
        documentation: "Interpolate between two values with a scalar weight.",
        insert_text: "mix",
        insert_text_format: None,
        sort_group: "31",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "dot",
        kind: CompletionItemKind::FUNCTION,
        detail: "Dot product",
        documentation: "Compute the dot product of two vectors.",
        insert_text: "dot",
        insert_text_format: None,
        sort_group: "31",
        contexts: VALUE_CONTEXTS,
    },
    CompletionSpec {
        label: "normalize",
        kind: CompletionItemKind::FUNCTION,
        detail: "Normalize a vector",
        documentation: "Scale a vector to unit length.",
        insert_text: "normalize",
        insert_text_format: None,
        sort_group: "31",
        contexts: VALUE_CONTEXTS,
    },
];

pub const ATTRIBUTE_SPECS: &[CompletionSpec] = &[
    CompletionSpec {
        label: "vertex",
        kind: CompletionItemKind::PROPERTY,
        detail: "Vertex entry point attribute",
        documentation:
            "Mark a function as a vertex shader entry point.\n\n```shadml\n@vertex\nmain = ...\n```",
        insert_text: "vertex",
        insert_text_format: None,
        sort_group: "00",
        contexts: ATTRIBUTE_CONTEXTS,
    },
    CompletionSpec {
        label: "fragment",
        kind: CompletionItemKind::PROPERTY,
        detail: "Fragment entry point attribute",
        documentation: "Mark a function as a fragment shader entry point.",
        insert_text: "fragment",
        insert_text_format: None,
        sort_group: "00",
        contexts: ATTRIBUTE_CONTEXTS,
    },
    CompletionSpec {
        label: "compute",
        kind: CompletionItemKind::PROPERTY,
        detail: "Compute entry point attribute",
        documentation: "Mark a function as a compute shader entry point.",
        insert_text: "compute",
        insert_text_format: None,
        sort_group: "00",
        contexts: ATTRIBUTE_CONTEXTS,
    },
    CompletionSpec {
        label: "workgroup_size",
        kind: CompletionItemKind::PROPERTY,
        detail: "Workgroup size attribute",
        documentation:
            "Set the compute workgroup dimensions.\n\n```shadml\n@workgroup_size(64, 1, 1)\n```",
        insert_text: "workgroup_size(${1:64}, ${2:1}, ${3:1})",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "00",
        contexts: ATTRIBUTE_CONTEXTS,
    },
    CompletionSpec {
        label: "group",
        kind: CompletionItemKind::PROPERTY,
        detail: "Bind group attribute",
        documentation: "Specify the resource bind group index.",
        insert_text: "group(${1:0})",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "00",
        contexts: ATTRIBUTE_CONTEXTS,
    },
    CompletionSpec {
        label: "binding",
        kind: CompletionItemKind::PROPERTY,
        detail: "Binding attribute",
        documentation: "Specify the binding index within a bind group.",
        insert_text: "binding(${1:0})",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "00",
        contexts: ATTRIBUTE_CONTEXTS,
    },
    CompletionSpec {
        label: "location",
        kind: CompletionItemKind::PROPERTY,
        detail: "Location attribute",
        documentation: "Specify an input or output location.",
        insert_text: "location(${1:0})",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "00",
        contexts: ATTRIBUTE_CONTEXTS,
    },
    CompletionSpec {
        label: "builtin",
        kind: CompletionItemKind::PROPERTY,
        detail: "Builtin attribute",
        documentation: "Bind a parameter or field to a WGSL builtin.",
        insert_text: "builtin(${1:global_invocation_id})",
        insert_text_format: Some(InsertTextFormat::SNIPPET),
        sort_group: "00",
        contexts: ATTRIBUTE_CONTEXTS,
    },
];

pub fn all_completion_specs() -> impl Iterator<Item = &'static CompletionSpec> {
    KEYWORD_SPECS
        .iter()
        .chain(TYPE_SPECS.iter())
        .chain(BUILTIN_SPECS.iter())
        .chain(ATTRIBUTE_SPECS.iter())
}

pub fn lookup_completion_spec(
    label: &str,
    context: CompletionContext,
) -> Option<&'static CompletionSpec> {
    all_completion_specs().find(|spec| spec.label == label && spec.contexts.contains(&context))
}

pub fn spec_matches_context(spec: &CompletionSpec, context: CompletionContext) -> bool {
    spec.contexts.contains(&context)
}

pub fn completion_item_from_spec(spec: &CompletionSpec) -> CompletionItem {
    CompletionItem {
        label: spec.label.to_owned(),
        kind: Some(spec.kind),
        detail: Some(spec.detail.to_owned()),
        insert_text: Some(spec.insert_text.to_owned()),
        insert_text_format: spec.insert_text_format,
        documentation: Some(Documentation::MarkupContent(MarkupContent {
            kind: MarkupKind::Markdown,
            value: format!("**{}**\n\n{}", spec.detail, spec.documentation),
        })),
        sort_text: Some(format!("{}-{}", spec.sort_group, spec.label)),
        filter_text: Some(spec.label.to_owned()),
        ..Default::default()
    }
}
