[[language]]
name = "fwgsl"
scope = "source.fwgsl"
injection-regex = "fwgsl"
file-types = ["fwgsl"]
comment-token = "--"
block-comment-tokens = { start = "{-", end = "-}" }
indent = { tab-width = 2, unit = "  " }
language-servers = ["fwgsl-lsp"]
auto-format = true

[language-server.fwgsl-lsp]
command = "fwgsl-lsp"

[[grammar]]
name = "fwgsl"
source = { path = "../../tree-sitter-fwgsl" }
