[[language]]
name = "shadml"
scope = "source.shadml"
injection-regex = "shadml"
file-types = ["shadml"]
comment-token = "--"
block-comment-tokens = { start = "{-", end = "-}" }
indent = { tab-width = 2, unit = "  " }
language-servers = ["shadml-lsp"]
auto-format = true

[language-server.shadml-lsp]
command = "shadml-lsp"

[[grammar]]
name = "shadml"
